GRANT USAGE ON SCHEMA public TO vahter_bot_ban_service;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO vahter_bot_ban_service;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO vahter_bot_ban_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO vahter_bot_ban_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO vahter_bot_ban_service;
