name: Build and test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Tests
      run: dotnet test -c Release --logger trx --results-directory TestResults
      
    # upload test results
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    # report test results
    - uses: dorny/test-reporter@v1
      with:
        artifact: TestResults
        name: .NET Tests
        path: '*.trx'
        reporter: dotnet-trx
