name: Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_bot-build.yml
    with:
      test-command: >-
dotnet test tests/VahterBanBot.Tests/VahterBanBot.Tests.fsproj
-c Release --logger "trx;LogFileName=test-results.trx"
--logger "console;verbosity=detailed"
