name: Test results

on:
  # Run this workflow after the testing workflow completes
  workflow_run:
    workflows:
      - CI
      - CD
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Extract the test result files from the artifacts
    - uses: dorny/test-reporter@v1
      with:
        name: Test results
        artifact: test-results
        path: "**/*.trx"
        reporter: dotnet-trx
        fail-on-error: true
